Global:
  feat_dim: 512
  M_POINT: 1024
  GRASPNESS_THRESHOLD: 0.1
  SUCTIONESS_THRESHOLD: 0.2
  NUM_VIEW: 300
  NUM_ANGLE: 12
  NUM_DEPTH: 4
  # [grasp, suction, both]
  training_branch: 'grasp'

Backbone:
  # [ResUnet, ResUnet_PA, ResUnet_CA, ResUnet_PCA, 'Pointnet2']
  name: 'Pointnet2'
  in_channels: 3

CloudCrop:
  nsample: 16
  hmin: -0.02
  hmax: 0.04
  cylinder_radius: 0.05
  out_dim: 512


